y, z = 10, 6
a = y + z
b = y - z
c = y / z
d = y // z #Divide without remainder
e = y*z
f = y**z #y^(z) "Power"
g = y^z
h = y%z
i = y - y/z * z
print("a=", a, type(a))
print("b=", b, type(b))
print("c=", c, type(c))
print("d=", d, type(d))
print("e=", e, type(e))
print("f=", f, type(f))
print("g=", g, type(g))
print("h=", h, type(h))
print("i=", i, type(i))